[package]
name = "dson-p2p-todo"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dson = "0.3.0"
rand = "0.8"
ratatui = "0.29.0"
rmp-serde = "1.3.0"
serde = { version = "1.0.228", features = ["derive"] }
socket2 = { version = "0.6.1", features = ["all"] }
